<?php
/**
 * The panel's only entry point.
 *
 * Every page, form post and JSON call arrives here. A listener's requests are
 * answered by lib/public.php; everything else is the panel, dispatched by
 * lib/router.php. Nothing else in this directory is reachable over HTTP: the
 * code lives in lib/, which .htaccess denies, and only engine/, media/ and
 * player/ contain public static files. Station data is generated by PHP.
 */

declare(strict_types=1);

// Said before anything newer than this is even read: the rest will not parse.
if (PHP_VERSION_ID < 80300) {
    http_response_code(503);
    header('Content-Type: text/plain; charset=utf-8');
    exit('52Hertz needs PHP 8.3 or newer; this server has PHP ' . PHP_VERSION . ".\n");
}

// A listener's requests - the clock, a station's feed, its app manifest and
// icons, its stream - are answered first, without loading the panel at all.
require __DIR__ . '/lib/public.php';
if (dispatch_public()) {
    exit;
}

require __DIR__ . '/lib/router.php';

// A server that cannot run the panel says so in words, before the database
// is touched.
if ($problems = server_problems()) {
    show_server_problems($problems);
}
migrate();
dispatch();
