<?php
/**
 * What a listener's request reaches: the clock, a station's feed, its app
 * manifest and icons, and its stream.
 *
 * index.php answers these before the panel is loaded at all. Every listener
 * asks for them many times an hour, and none of them needs a session, the
 * page layout or any of the panel's templates, so none of that is compiled
 * for them. The clock does not even open the database.
 */

declare(strict_types=1);

require_once __DIR__ . '/bootstrap.php';

/** Public endpoints are read-only. Reject unexpected verbs before doing work. */
function public_read_method(): bool
{
    $method = strtoupper((string) ($_SERVER['REQUEST_METHOD'] ?? 'GET'));
    if (in_array($method, ['GET', 'HEAD', 'OPTIONS'], true)) {
        return true;
    }
    header('Allow: GET, HEAD, OPTIONS');
    http_response_code(405);
    return false;
}

/**
 * The clock reference players use. Public, tiny, uncacheable, and reached
 * before any session is started — it coordinates nothing and answers one
 * question.
 */
function page_time(): void
{
    if (!public_read_method()) return;
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store, max-age=0');
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: GET, HEAD, OPTIONS');

    if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') {
        http_response_code(204);
        return;
    }

    echo json_encode([
        'nowMs'      => (int) round(microtime(true) * 1000),
        'iso'        => gmdate('c'),
        'resolution' => 'milliseconds, server clock, no correction applied',
    ], JSON_UNESCAPED_SLASHES);
}

/** Headers shared by public station data generated by PHP. */
function public_station_headers(string $contentType, string $etag, int $maxAge = 0): bool
{
    if (!public_read_method()) return true;
    header('Content-Type: ' . $contentType);
    header('Cache-Control: public, max-age=' . $maxAge . ', must-revalidate');
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: GET, HEAD, OPTIONS');
    header('ETag: ' . $etag);
    header('X-Content-Type-Options: nosniff');
    if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') {
        http_response_code(204);
        return true;
    }
    if (str_contains((string) ($_SERVER['HTTP_IF_NONE_MATCH'] ?? ''), $etag)) {
        http_response_code(304);
        return true;
    }
    return false;
}

/** Return the station's dynamic, conditionally cached broadcast feed. */
function page_station_feed(string $stationId): void
{
    $feed = publication_feed($stationId);
    if ($feed === null) {
        json_out(['error' => 'station not found or not published'], 404);
    }
    $etag = '"52hertz-' . $stationId . '-r' . (int) $feed['revision'] . '"';
    if (public_station_headers('application/json; charset=utf-8', $etag)) return;
    if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'HEAD') {
        echo json_encode($feed, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR);
    }
}

function panel_public_path(): string
{
    $script = str_replace('\\', '/', (string) ($_SERVER['SCRIPT_NAME'] ?? '/index.php'));
    $directory = rtrim(str_replace('\\', '/', dirname($script)), '/');
    return ($directory === '' || $directory === '.') ? '/' : $directory . '/';
}

/** A station-specific PWA manifest generated from its latest live snapshot. */
function page_station_manifest(string $stationId): void
{
    $publication = latest_publication($stationId);
    if ($publication === null) {
        json_out(['error' => 'station not found or not published'], 404);
    }
    $etag = '"52hertz-' . $stationId . '-r' . (int) $publication['revision'] . '-manifest"';
    if (public_station_headers('application/manifest+json; charset=utf-8', $etag, 300)) return;
    if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'HEAD') {
        // The request's own address says which form it came by: a rewrite
        // leaves REQUEST_URI as the listener's browser sent it.
        $path = (string) parse_url((string) ($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_PATH);
        echo json_encode(
            station_manifest($publication, panel_public_path(), str_ends_with($path, '/manifest.webmanifest')),
            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR
        );
    }
}

/** Exact-size favicon/app artwork; conditional requests avoid regeneration. */
function page_station_icon(string $stationId): void
{
    $publication = latest_publication($stationId);
    if ($publication === null) {
        http_response_code(404);
        return;
    }
    $size = (int) ($_GET['size'] ?? 0);
    $maskable = ($_GET['maskable'] ?? '') === '1';
    if (!in_array($size, [192, 512], true) || ($maskable && $size !== 512)) {
        http_response_code(400);
        return;
    }
    $variant = $maskable ? 'maskable' : 'any';
    $etag = '"52hertz-' . $stationId . '-r' . (int) $publication['revision'] . "-icon-$size-$variant\"";
    if (public_station_headers('image/png', $etag, 300)) return;
    if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'HEAD') {
        echo station_icon_png($publication, $size, $maskable);
    }
}

/**
 * Answer a listener's request, or return false and leave it to the panel.
 *
 * Deliberately before any session: a listener's browser asks for these many
 * times an hour, and must never be handed a session cookie for them.
 */
function dispatch_public(): bool
{
    $page = (string) ($_GET['p'] ?? '');
    if ($page === 'time') {
        page_time();
        return true;
    }
    if (!in_array($page, ['station-feed', 'station-manifest', 'station-icon', 'stream'], true)) {
        return false;
    }

    // Reject writes and answer CORS preflight before loading the publisher or
    // opening SQLite. Public listener routes are strictly read-only.
    if (!public_read_method()) {
        return true;
    }
    if (strtoupper((string) ($_SERVER['REQUEST_METHOD'] ?? 'GET')) === 'OPTIONS') {
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: GET, HEAD, OPTIONS');
        http_response_code(204);
        return true;
    }

    require_once __DIR__ . '/publisher.php';
    migrate();
    $id = (string) ($_GET['id'] ?? '');
    switch ($page) {
        case 'station-feed':     page_station_feed($id);     break;
        case 'station-manifest': page_station_manifest($id); break;
        case 'station-icon':     page_station_icon($id);     break;
        case 'stream':
            require_once __DIR__ . '/stream.php';
            page_station_stream($id);
            break;
    }
    return true;
}
